### ISSUE TITLE
Project navigation non-existent in mobile view

### ISSUE THREAD

**Issue by SmileyChris** [farirpgs/fari-community#10]
Take a look at, for example, the [Charge RPG](https://fari.community/creators/fari-rpgs/projects/charge) project in mobile view. There's no hamburger or way to access the project navigation shown in the left when in a wider profile screen.

**Comment by RPDeshaies** [comment]
That's true yeah. I'll try to work on something soon. Cheers

**Comment by RPDeshaies** [comment]
This is now live!
