### ISSUE TITLE
Minor typo correction in Character Creation Recap

### ISSUE THREAD

**Issue by Taellosse** [farirpgs/fari-community#86]
At the end of the Character Creation chapter, in [The Character Sheet summary](https://fari.community/creators/fari-rpgs/projects/charge/creating-your-character?scrollTo=the-character-sheet) the 4th bullet point reads, 

>-  A stress clock and condition to represent the ~~state~~ physical and mental state of a character.

_(strikethrough added to indicate error)_

**Comment by RPDeshaies** [comment]
good catch! Updating~
