### ISSUE TITLE
Markdown typo in Consequences section of Mechanics Chapter

### ISSUE THREAD

**Issue by Taellosse** [farirpgs/fari-community#87]
Under [Worse Condition](https://fari.community/creators/fari-rpgs/projects/charge/consequences?scrollTo=worse-condition), in the second paragraph it reads,

> You also need to update your **condition ** to represent the new state your character is in.

There is an unwanted space between "condition" and the closing '**' intended to turn the word bold.

**Comment by RPDeshaies** [comment]
ah good catch thank you!
